### ISSUE TITLE
Tested on mobile—safe to allow mobile I think

### ISSUE THREAD

**Issue by Moonbase59** [kurakart/garble-text#3]
I tested your plugin on an Android mobile today, and it works fine, even with my added CSS snippet. Unfortunately I have no iOS device to test, but I think it should be safe to change your `manifest.json` to allow mobile use:

```json
"isDesktopOnly": false
```

Thanks!

![Screenshot_20210824-192137](https://user-images.githubusercontent.com/3706922/130662702-5519a065-ba39-44b6-bfd3-34deaf0d92df.png)

**Comment by valentine195** [comment]
Also works on iOS with `isDesktopOnly` set to false.

**Comment by Moonbase59** [comment]
Now heavily promoted at https://forum.obsidian.md/t/garble-text-on-screen-to-hide-private-info-with-added-features/23143 :grin:

**Comment by kurakart** [comment]
No moonbase what are you doing?? Stop making this popular 😅😅 I'm working on the hover css, enabling on mobile, and the toolbar icon right now. Will credit appropriately 😊
